Update run.yml

diff --git a/.github/workflows/run.yml b/.github/workflows/run.yml
--- a/.github/workflows/run.yml
+++ b/.github/workflows/run.yml
@@ -1,11 +1,7 @@
-# This is a basic workflow to help you get started with Actions
-
 name: Trigger Jenkins Job on Pull Request
 
 on:
   # Triggers the workflow on push or pull request events but only for the "main" branch
-  push:
-    branches: [ "main" ]
   pull_request:
     branches: [ "main" ]
 
@@ -17,6 +13,23 @@ jobs:
         env:
           JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
         run: |
-          curl -X POST https://66fcb0e9fb53496894b8ba363b676c3e-2887499781-8080-host12nc.environments.katacoda.com/job/test/build \
-          --user admin:$JENKINS_API_TOKEN \
-
+          # Trigger Jenkins job and get queue item number
+          queue_url=$(curl -X POST https://66fcb0e9fb53496894b8ba363b676c3e-2887499781-8080-host12nc.environments.katacoda.com/job/test/build \
+            --user admin:$JENKINS_API_TOKEN 
+          
+          # Extract queue item number
+          queue_item=$(basename "$queue_url")
+          
+          # Poll Jenkins job status until it finishes
+          status=""
+          while [ "$status" != "SUCCESS" ] && [ "$status" != "FAILURE" ]; do
+            status=$(curl -s -X GET "https://66fcb0e9fb53496894b8ba363b676c3e-2887499781-8080-host12nc.environments.katacoda.com/queue/item/$queue_item/api/json" \
+              --user admin:$JENKINS_API_TOKEN | jq -r .executable.result)
+            sleep 5
+          done
+          
+          # Fail GitHub Actions workflow if Jenkins job fails
+          if [ "$status" != "SUCCESS" ]; then
+            echo "Jenkins job failed."
+            exit 1
+          fi
